### ISSUE TITLE
apk闪退

### ISSUE THREAD

**Issue by BroadswordZhang** [paleomoon/darknet-ncnn-android#2]
在模拟器上安装成功，但双击闪退

**Comment by paleomoon** [comment]
查看Logcat报错信息定位问题。建议使用真机调试。

**Comment by BroadswordZhang** [comment]
java.lang.UnsatisfiedLinkError: dlopen failed: library "libomp.so" not found 报错，网上Google了一遍，没找到有效方式

**Comment by paleomoon** [comment]
https://github.com/Tencent/ncnn/issues/1771
